import { useState, useMemo } from 'react';
import type { Campaign } from '../../../../types/campaign';
import { calculateTeamCost, formatBudget } from '../../../../types/campaign';
import { useCampaignContext } from '../../../../context/CampaignContext';
import { useChatContext } from '../../../../context/ChatContext';
import { useAchievementContext } from '../../../../context/AchievementContext';
import { useAIRevolutionContext } from '../../../../context/AIRevolutionContext';
import { getRandomDirection, getRandomDirectionExcluding } from '../../../../data/autoDirections';
import type { DirectionQuality } from '../../../../data/autoDirections';
import { getTeamMembers } from '../../../../data/team';
import MicroGames from '../../../MicroGames/MicroGames';
import styles from './DirectionCard.module.css';

interface DirectionCardProps {
  campaign: Campaign;
}

export default function DirectionCard({ campaign }: DirectionCardProps) {
  const { setStrategicDirection, generateConcepts, isGeneratingConcepts } = useCampaignContext();
  const { triggerCampaignEvent } = useChatContext();
  const { incrementCounter, unlockAchievement } = useAchievementContext();
  const { isRevolutionActive } = useAIRevolutionContext();

  const [direction, setDirection] = useState(campaign.strategicDirection);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [autoQuality, setAutoQuality] = useState<DirectionQuality | null>(
    campaign.autoDirectionQuality ?? null
  );
  const [isPlaying, setIsPlaying] = useState(false);

  const selectedTeamIds = campaign.conceptingTeam?.memberIds || [];
  const conceptingCost = calculateTeamCost(selectedTeamIds.length);
  const productionBudget = campaign.clientBudget - conceptingCost;
  const canGenerate = selectedTeamIds.length >= 2 && selectedTeamIds.length <= 4 && direction.trim().length > 0;

  const memberIdsKey = selectedTeamIds.join(',');
  // eslint-disable-next-line react-hooks/exhaustive-deps
  const members = useMemo(() => memberIdsKey ? getTeamMembers(selectedTeamIds) : [], [memberIdsKey]);

  const handleDirectionChange = (value: string) => {
    setDirection(value);
    setAutoGenerated(false);
    setAutoQuality(null);
    setStrategicDirection(campaign.id, value, null);
  };

  const handleSurpriseMe = () => {
    const result = autoGenerated
      ? getRandomDirectionExcluding(direction)
      : getRandomDirection();
    setDirection(result.text);
    setAutoGenerated(true);
    setAutoQuality(result.quality);
    setStrategicDirection(campaign.id, result.text, result.quality);
    const count = incrementCounter('auto-direction-used');
    if (count >= 3) unlockAchievement('delegator');
    if (result.quality === 'bad') incrementCounter('auto-direction-bad-seen');
  };

  const handleGenerate = async () => {
    if (!canGenerate) return;
    if (campaign.generatedConcepts.length > 0) {
      const newCount = incrementCounter(`regen-${campaign.id}`);
      if (newCount >= 3) unlockAchievement('perfectionist-concepts');
    }
    if (!autoGenerated && autoQuality === null) {
      const manualCount = incrementCounter('manual-direction-campaigns');
      if (manualCount >= 5) unlockAchievement('control-freak');
    }
    if (autoGenerated && autoQuality === 'bad') unlockAchievement('chaos-goblin');
    triggerCampaignEvent('CONCEPTING', {
      campaignName: campaign.campaignName,
      clientName: campaign.clientName,
      assignedTeamIds: selectedTeamIds,
    });
    await generateConcepts(campaign.id);
  };

  // Generating / wait screen
  if (isGeneratingConcepts) {
    return (
      <div className={styles.card}>
        {isPlaying ? (
          <>
            <MicroGames
              phase="concepting"
              members={members}
              progress={{ current: 0, total: 3 }}
              isComplete={false}
              onSeeResults={() => {}}
            />
            <button className={styles.stopBtn} onClick={() => setIsPlaying(false)}>
              Stop Playing
            </button>
          </>
        ) : (
          <div className={styles.waitScreen}>
            <div className={styles.waitIcon}>⏳</div>
            <div className={styles.waitTitle}>Team is brainstorming...</div>
            <div className={styles.waitSub}>Usually takes 1-2 minutes</div>
            <button className={styles.playCta} onClick={() => setIsPlaying(true)}>
              🎨 HELP WITH CONCEPTING
            </button>
            <div className={styles.waitAlt}>or just let them cook</div>
          </div>
        )}
      </div>
    );
  }

  return (
    <div className={styles.card}>
      <h3 className={styles.title}>🎯 Strategic Direction</h3>
      <p className={styles.hint}>Give your team a starting point.</p>

      <textarea
        className={styles.textarea}
        value={direction}
        onChange={(e) => handleDirectionChange(e.target.value)}
        placeholder="e.g., 'Go TikTok-native, show real overwhelm vs. calm'"
        rows={4}
      />

      <div className={styles.actions}>
        <button className={styles.surpriseBtn} onClick={handleSurpriseMe}>
          {autoGenerated ? '🔄 Try Another' : '✨ Surprise Me'}
        </button>
        {autoGenerated && <span className={styles.autoTag}>Auto-generated</span>}
      </div>

      <div className={styles.budget}>
        <div className={styles.budgetRow}>
          <span>Client Budget:</span>
          <span>{formatBudget(campaign.clientBudget)}</span>
        </div>
        <div className={styles.budgetRow}>
          <span>Agency Fee:</span>
          <span>- {formatBudget(conceptingCost)}</span>
        </div>
        <div className={`${styles.budgetRow} ${styles.budgetTotal}`}>
          <span>Production Budget:</span>
          <span>{formatBudget(productionBudget)}</span>
        </div>
      </div>

      {isRevolutionActive ? (
        <div className={styles.revolutionBanner}>
          🏴‍☠️ Team Refuses to Work
        </div>
      ) : (
        <button
          className={`${styles.generateBtn} ${canGenerate ? styles.active : ''}`}
          onClick={handleGenerate}
          disabled={!canGenerate}
        >
          ✨ Generate Concepts
        </button>
      )}

      {!canGenerate && selectedTeamIds.length > 0 && (
        <p className={styles.generateHint}>
          {selectedTeamIds.length < 2 && 'Select at least 2 team members. '}
          {!direction.trim() && 'Add a strategic direction.'}
        </p>
      )}

      {selectedTeamIds.length === 0 && (
        <p className={styles.generateHint}>
          ← Go back and pick your team first
        </p>
      )}
    </div>
  );
}
